name: onlytest
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Get dependencies
        run: npm ci

      - name: Format check
        run: npm run fmt:check

      - name: Lint code
        run: npm run lint
